### ISSUE TITLE
fonts not included in output

### ISSUE THREAD

**Issue by danielroe** [antfu-collective/vite-plugin-inspect#137]
### Describe the bug

CSS tries to load some fonts:

```css
@font-face {
  font-family: 'DM Mono';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(/assets/fonts/dmmono-989a58ac.woff2) format('woff2');
  unicode-range: U+0100-02AF, U+0304, U+0308, U+0329, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
```
> https://unpkg.com/browse/vite-plugin-inspect@10.1.1/dist/client/assets/index-77TPuc99.css

However these are not located in the published package: https://unpkg.com/browse/vite-plugin-inspect@10.1.1/dist/client/assets/

### Reproduction

https://unpkg.com/browse/vite-plugin-inspect@10.1.1/dist/client/assets/

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 29.46 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.local/share/mise/installs/node/22.12.0/bin/node
    npm: 10.9.0 - ~/.local/share/mise/installs/node/22.12.0/bin/npm
    pnpm: 10.2.1 - ~/.local/share/mise/installs/node/22.12.0/bin/pnpm
    bun: 1.2.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 132.0.6834.160
    Chrome Canary: 135.0.7009.0
    Safari: 17.6
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)
